
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'

export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST'
export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST'

export const FIREBASE_CONNECTED = 'FIREBASE_CONNECTED'
export const FIREBASE_DISCONNECTED = 'FIREBASE_DISCONNECTED'
